os:
- osx
- linux
- windows

language: node_js
node_js:
- node
- 11
- 10
- 10.15.1
- 10.15.0
- 10.14.2
- 10.14.1
- 10.14.0
- 10.13
- 9
- 8
- 8.15
- 8.14.1
- 8.14.0
- 8.13
- 8.12
- 8.11.4
- 8.11.3
- 8.11.2
- 8.11.1
- 8.11.0
- 8.10
- 8.9.4
- 8.9.3
- 8.9.2
- 8.9.1
- 8.9.0
- 7
- 7.6
after_success: npm run coveralls
